// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Reporting.Persistence;

#nullable disable

namespace Wms.Reporting.Persistence.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.BuildingBlocks.Application.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_code");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Traceparent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("traceparent");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("AggregateType", "AggregateId", "OccurredAt")
                        .HasDatabaseName("ix_audit_log_aggregate_type_aggregate_id_occurred_at");

                    b.ToTable("audit_log", "infrastructure");
                });

            modelBuilder.Entity("Wms.BuildingBlocks.Application.Messaging.DeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("error");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("LogicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logical_name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<string>("Traceparent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("traceparent");

                    b.Property<string>("Tracestate")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("tracestate");

                    b.HasKey("Id")
                        .HasName("pk_dead_letter");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_dead_letter_event_id");

                    b.ToTable("dead_letter", "infrastructure");
                });

            modelBuilder.Entity("Wms.BuildingBlocks.Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("HandlerType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handler_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId", "HandlerType")
                        .HasName("pk_inbox");

                    b.ToTable("inbox", "infrastructure");
                });

            modelBuilder.Entity("Wms.BuildingBlocks.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<string>("LogicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logical_name");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Traceparent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("traceparent");

                    b.Property<string>("Tracestate")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("tracestate");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_processed_at_occurred_at");

                    b.ToTable("outbox", "infrastructure");
                });

            modelBuilder.Entity("Wms.Reporting.Projections.DispatchSummary", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("TotalVolume")
                        .HasColumnType("integer")
                        .HasColumnName("total_volume");

                    b.Property<int>("WaveCount")
                        .HasColumnType("integer")
                        .HasColumnName("wave_count");

                    b.HasKey("Day")
                        .HasName("pk_dispatch_summary");

                    b.ToTable("dispatch_summary", "reporting");
                });

            modelBuilder.Entity("Wms.Reporting.Projections.OperatorActivity", b =>
                {
                    b.Property<string>("OperatorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operator_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("PickCount")
                        .HasColumnType("integer")
                        .HasColumnName("pick_count");

                    b.Property<int>("PutawayCount")
                        .HasColumnType("integer")
                        .HasColumnName("putaway_count");

                    b.HasKey("OperatorId", "Day")
                        .HasName("pk_operator_activity");

                    b.ToTable("operator_activity", "reporting");
                });

            modelBuilder.Entity("Wms.Reporting.Projections.ReceivingSummary", b =>
                {
                    b.Property<string>("SupplierId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("supplier_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("GrCount")
                        .HasColumnType("integer")
                        .HasColumnName("gr_count");

                    b.Property<int>("ReceivedQty")
                        .HasColumnType("integer")
                        .HasColumnName("received_qty");

                    b.Property<int>("RejectedQty")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_qty");

                    b.HasKey("SupplierId", "Day")
                        .HasName("pk_receiving_summary");

                    b.ToTable("receiving_summary", "reporting");
                });

            modelBuilder.Entity("Wms.Reporting.Projections.StockOnHandView", b =>
                {
                    b.Property<string>("WarehouseId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("warehouse_id");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("Batch")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("batch");

                    b.Property<int>("QtyOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("qty_on_hand");

                    b.HasKey("WarehouseId", "Sku", "Batch")
                        .HasName("pk_stock_on_hand_view");

                    b.ToTable("stock_on_hand_view", "reporting");
                });
#pragma warning restore 612, 618
        }
    }
}
